### ISSUE TITLE
Request: Allow config overrides for settings

### ISSUE THREAD

**Issue by timkelty** [davist11/Hon-ee-Pot-Captcha#2]
Would be great if we could override the settings in config.
Was going to use something like this, but got caught up with something else: https://gist.github.com/3039077

I'll get to it eventually, but if I don't, just sticking it here in case you want to do it.

Thanks!

**Comment by davist11** [comment]
Good call, I love addons that provide config overrides. I'll add this to my todo list.

**Comment by davist11** [comment]
I finally got around to adding those config overrides in:

<pre>$config['honeepot_field'] = 'honeepot';
$config['honeepot_error'] = 'Sorry, but we think you might be a robot.';</pre>


Thanks for the suggestion!

**Comment by timkelty** [comment]
nice!
